### ISSUE TITLE
Proxy do not respect sub router paths

### ISSUE THREAD

**Issue by 4ov** [asos-craigmorten/opine-http-proxy#9]
# Issue

Setup:

- Deno Version: ` 1.15.2 (release, x86_64-unknown-linux-gnu)`
- v8 Version: `9.5.172.19`
- Typescript Version:  `4.4.2`
- Opine HTTP Proxy Version: `2.9.0`
- Opine Version: `1.8.0`

## Details

Proxy do not respect sub router paths
#### Example
```js
import { opine, Router } from 'https://deno.land/x/opine@1.8.0/mod.ts'
import { proxy } from 'https://deno.land/x/opineHttpProxy@2.9.0/mod.ts'

const app = opine()
const router = Router()

router.use(proxy("https://google.com"))

app.use('/sub-route', router)

app.listen(5000)
```
#### What i expect
to load resources in the `/sub-path`

#### What is see

![Screenshot from 2021-10-31 22-47-33](https://user-images.githubusercontent.com/54923746/139600760-6d8beaa8-7885-4922-b8f7-d56b722f3158.png)

_i think there is should be an option to set the base url of the proxy_
thanks in advance

**Comment by cmorten** [comment]
Hey @4ov 👋 

Apologies not quite following what the issue is? Do you mind sharing the request you are making to the server, what the proxied request is, and what your expected proxies request should be?

If you need to modified the proxied request url you can use https://github.com/asos-craigmorten/opine-http-proxy#proxyrequrldecoratorurl-req-supports-promise-form
